### ISSUE TITLE
Inquiry on your custom environment in HoloOcean

### ISSUE THREAD

**Issue by SYZ2048** [guilhermecdo/Holoocean-imaging-sonar#1]
Hope this message finds you well. I came across your issue on the HoloOcean GitHub repository and was particularly interested in the video of your simulated underwater environment. I would like to inquire about some details related to your setup.

Did you use the AUV provided by HoloOcean for your simulation?How did you import HoloOcean's AUV into your custom underwater environment?
I attempted to directly copy the Content folder from HoloOcean's worlds into my project, but unfortunately, it was unsuccessful. I would greatly appreciate it if you could share the steps and workflow you followed to set up your simulation environment.

Thank you very much for your time and assistance.

**Comment by guilhermecdo** [comment]
Hi, I did use the simulator's standard AUV. As for my world, I created it using the Unreal Editor, as shown in the holoOcean documentation.

**Comment by SYZ2048** [comment]
@guilhermecdo Thank you! I'm trying to develop a custom environment on UE4.

And, I would like to inquire about the detailed settings for your custom environment. Based on the exampleLevel provided by the official documentation, I have added a WaterBodyLake, a Landscape (to place my WaterBodyLake), and a Cube (as the observation target). However, in my sonar images, neither the Landscape nor the Cube is displayed. I found a similar issue in the Holoocean issues page, and I suspect it might be related to the "collision" settings, but I have not yet found the appropriate settings.

Could you please share if there are any special settings for each actor in your custom environment?

Thank you very much for reading my question.
